#!/usr/bin/env python3
import json
import os
from datetime import datetime

class CodeExporter:
    def __init__(self):
        self.formats = ['python', 'curl', 'javascript', 'nodejs']
    
    def export_python_code(self, request_data):
        """Generate Python code for the working request"""
        code = f"""#!/usr/bin/env python3
import requests
import json

# API Request generated by Universal API Tester
# Generated on: {datetime.now().isoformat()}

def make_request():
    url = "{request_data['url']}"
    method = "{request_data.get('method', 'GET')}"
    
    headers = {json.dumps(request_data.get('headers', {}), indent=4)}
    """
        
        if request_data.get('cookies'):
            code += f"""
    cookies = {json.dumps(request_data.get('cookies', {}), indent=4)}
    """
        else:
            code += "\n    cookies = None\n"
        
        if request_data.get('json_body'):
            code += f"""
    json_data = {json.dumps(request_data.get('json_body', {}), indent=4)}
    """
        elif request_data.get('data'):
            code += f"""
    data = "{request_data.get('data')}"
    """
        else:
            code += "\n    data = None\n"
        
        code += """
    response = requests.request(
        method=method,
        url=url,
        headers=headers,"""
        
        if request_data.get('cookies'):
            code += "\n        cookies=cookies,"
        
        if request_data.get('json_body'):
            code += "\n        json=json_data,"
        elif request_data.get('data'):
            code += "\n        data=data,"
        
        code += """
        timeout=30
    )
    
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.text}")
    
    return response

if __name__ == "__main__":
    make_request()
"""
        return code
    
    def export_curl_code(self, request_data):
        """Generate cURL command"""
        curl_cmd = f"curl -X {request_data.get('method', 'GET')} \\\n"
        curl_cmd += f"  '{request_data['url']}' \\\n"
        
        for key, value in request_data.get('headers', {}).items():
            curl_cmd += f"  -H '{key}: {value}' \\\n"
        
        if request_data.get('json_body'):
            json_str = json.dumps(request_data['json_body'])
            curl_cmd += f"  --data-raw '{json_str}' \\\n"
        elif request_data.get('data'):
            curl_cmd += f"  --data-raw '{request_data['data']}' \\\n"
        
        curl_cmd += "  --compressed"
        
        return curl_cmd
    
    def export_javascript_code(self, request_data):
        """Generate JavaScript fetch code"""
        js_code = f"""// API Request generated by Universal API Tester
// Generated on: {datetime.now().isoformat()}

const url = '{request_data['url']}';
const method = '{request_data.get('method', 'GET')}';
"""
        
        js_code += f"""
const headers = {json.dumps(request_data.get('headers', {}), indent=2)};
"""
        
        if request_data.get('json_body'):
            js_code += f"""
const body = JSON.stringify({json.dumps(request_data.get('json_body', {}), indent=2)});
"""
        else:
            js_code += "\nconst body = null;\n"
        
        js_code += """
fetch(url, {
    method: method,
    headers: headers,
    body: body
})
.then(response => response.text())
.then(data => {
    console.log('Response:', data);
})
.catch(error => {
    console.error('Error:', error);
});
"""
        return js_code
    
    def save_code_file(self, code, filename, format_type):
        """Save code to file"""
        os.makedirs('exported_code', exist_ok=True)
        filepath = f"exported_code/{filename}.{format_type}"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(code)
        
        return filepath
